### ISSUE TITLE
Not working on firefox developer edition 

### ISSUE THREAD

**Issue by StyleShit** [noobfromvn/hackbar#3]
Hi,

Your work is awesome!
Unfortunately, it's not working on the dev edition, I can't see the icon and i get error:
```
Firefox can’t find the file at moz-extension://0ee24f21-4c63-43b6-a173-7e163e0360a1/hackbar/hackbar/hackbar-panel.html.
```

Firefox Dev Edition v59.0b3 (latest)

Thnx! :)

**Comment by noobfromvn** [comment]
Thank you! I updated version 1.0.5 to resolve this problem.
